services:
  product-management-service:
    build: .
    container_name: product-management-service
    expose:
      - "5000"
    networks:
      - my-microservices-net
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb

networks:
  my-microservices-net:
    external: true
